// Generated by scripts/generate-assets.mjs — do not edit.
import type { ImageMetadata } from 'astro';
import jsonFormatter480 from '../content/projects/json-formatter-480.webp';
import jsonFormatter960 from '../content/projects/json-formatter-960.webp';
import jsonFormatter1280 from '../content/projects/json-formatter-1280.webp';
import mau480 from '../content/projects/mau-480.webp';
import mau960 from '../content/projects/mau-960.webp';
import mau1280 from '../content/projects/mau-1280.webp';
import mdPreview480 from '../content/projects/md-preview-480.webp';
import mdPreview960 from '../content/projects/md-preview-960.webp';
import mdPreview1280 from '../content/projects/md-preview-1280.webp';
import stgEmail480 from '../content/projects/stg-email-480.webp';
import stgEmail960 from '../content/projects/stg-email-960.webp';
import stgEmail1280 from '../content/projects/stg-email-1280.webp';
import stringCompareOnline480 from '../content/projects/string-compare-online-480.webp';
import stringCompareOnline960 from '../content/projects/string-compare-online-960.webp';
import stringCompareOnline1280 from '../content/projects/string-compare-online-1280.webp';

export const PREVIEW_VARIANTS: Record<string, ImageMetadata[]> = {
	'json-formatter': [jsonFormatter480, jsonFormatter960, jsonFormatter1280],
	'mau': [mau480, mau960, mau1280],
	'md-preview': [mdPreview480, mdPreview960, mdPreview1280],
	'stg-email': [stgEmail480, stgEmail960, stgEmail1280],
	'string-compare-online': [stringCompareOnline480, stringCompareOnline960, stringCompareOnline1280],
};
